import { Button, LineEdit } from "std-widgets.slint";
export MainWindow := Window {
    title: "Kosevods";
    callback about_clicked <=> about.clicked;
    callback connect_clicked <=> connect_button.clicked;
    callback record_clicked <=> record_button.clicked;
    property <string> obs_ip <=> obs_ip.text;
    property <string> obs_port <=> obs_port.text;
    property <string> obs_pass <=> obs_pass.text;
    property <string> combatlog_path <=> combatlog.text;
    property <bool> obs_connected: false;
    property <bool> recording: false;

    VerticalLayout {
        HorizontalLayout { 
            Text {
                text: "OBS-Studio IP:";
                color: black;
                vertical-alignment: center;
                font-size: 16px;
            }
            obs_ip := LineEdit { 
                width: 200px;
                height: 30px;
                text: "localhost";
            }
        }
        HorizontalLayout { 
            Text {
                text: "OBS-Studio Port:";
                color: black;
                vertical-alignment: center;
                font-size: 16px;
            }
            obs_port := LineEdit { 
                width: 200px;
                height: 30px;
                text: "4444";
            }
        }
        HorizontalLayout { 
            Text {
                text: "OBS-Studio password:";
                color: black;
                vertical-alignment: center;
                font-size: 16px;
            }
            obs_pass := LineEdit { 
                width: 200px;
                height: 30px;
                text: "obswebsocket";
                input-type: InputType.password;
            }
        }
        
        HorizontalLayout {
            Text {
                text: "WowCombatLog.txt:";
                vertical-alignment: center;
                font-size: 16px;
            }
            combatlog := LineEdit { 
                width: 200px;
                height: 30px;
                text: "C:\\Users\\mw\\Documents\\WoWCombatLog.txt";
             }           
         }
         HorizontalLayout { 
            Text {
                text: "OBS Status:";
                font-size: 16px;
            }
            if obs_connected : Rectangle {
                min-width: 20px;
                min-height: 20px;
                max-width: 200px;
                max-height: 20px;
                background: green;
            }
            if !obs_connected : Rectangle {
                min-width: 20px;
                min-height: 20px;
                max-width: 200px;
                max-height: 20px;
                background: red;
            }
          }
          HorizontalLayout { 
            connect_button := Button { 
                text: "Connect to OBS";
                max-height: 40px;
             }
           }
        HorizontalLayout { 
            Text {
                text: "Auto Record Status: ";
                font-size: 16px;
            }
            if recording : Rectangle {
                min-width: 20px;
                min-height: 20px;
                max-width: 200px;
                max-height: 20px;
                background: green;
            }
            if !recording : Rectangle {
                min-width: 20px;
                min-height: 20px;
                max-width: 200px;
                max-height: 20px;
                background: red;
            }
         }
         HorizontalLayout { 
            record_button := Button {
                text: "Start Recording";
                max-height: 40px;
            }
        }

        HorizontalLayout { 
            Rectangle { 
                min-height: 40px;
                max-height: 100px;
             }
         }

        HorizontalLayout { 
            about := Button {
                text: "About";
                max-height: 40px;
            }
         }
    }
    
}